### ISSUE TITLE
Object has no attribute 'n_pred

### ISSUE THREAD

**Issue by VenkateshLab** [sollan/alma#26]
Hi, 
When i submit the data to lader run analysis. Im facing an error 
```
"Traceback (most recent call last):
  File "/Users/manojkumark/Desktop/alma/Panels/AnalyzeFootfall.py", line 832, in DisplayFootfall_UI_2
    self.Footfall_UI_2()
  File "/Users/manojkumark/Desktop/alma/Panels/AnalyzeFootfall.py", line 598, in Footfall_UI_2
    if self.n_pred is not None:
AttributeError: 'AnalyzeFootfallPanel' object has no attribute 'n_pred'
"
```
I have included my input for the analysis 
<img width="1316" alt="Screenshot 2023-01-06 at 09 31 05" src="https://user-images.githubusercontent.com/118877790/210928766-ddb92e23-3b99-4085-81a2-74492d6edc2f.png">

Input data looks like this. 
![Screenshot 2023-01-06 at 09 29 41](https://user-images.githubusercontent.com/118877790/210928771-cf00b214-8241-4ca1-89b7-f3f5e72ed292.png)

Error message. 

<img width="508" alt="Screenshot 2023-01-06 at 09 31 15" src="https://user-images.githubusercontent.com/118877790/210928784-1194a4ff-4893-4266-9aab-34e7c5d16531.png">

**Comment by sollan** [comment]
Hi! Apparently no footfalls were detected based on the input data. 

If this is not the case and you know there were footfalls in the corresponding video, please check the quality of your input data and the config file for the program. I noticed that you have included "limb" as a basis for footfall detection. This should most likely not be the case - "toe" seems to be the actual limb endpoint ("toe y" should be used, and not "toe x", since the method is based on depth / y coordinate values). If the recording / coordinate data doesn't reflect the animal movements accurately, for example if frame rate is too low to detect rapid footfalls, or if the DLC estimation output is bad/noisy, then the footfall detection won't work.

**Comment by VenkateshLab** [comment]
@sollan thanks i will redo the analysis in DLC. Thanks for your sugesstion.
