### ISSUE TITLE
Problem with preparing metadata 

### ISSUE THREAD

**Issue by aer2232** [sollan/alma#29]
Hello,

I am trying to launch alma.py and have encountered an issue at the `pip install -r requirements.txt` step. 
![snip1](https://user-images.githubusercontent.com/128635534/227007110-ad4c59b8-f99a-461e-b16e-dc466c535033.PNG)

The error says that the metadata preparation did not run successfully.
![snip2](https://user-images.githubusercontent.com/128635534/227012211-c5aea35b-fce2-458f-a8d5-c06d3124a2b3.PNG)

I am using a Windows computer with Python3.10 

Thanks,
Alex

**Comment by sollan** [comment]
Hi Alex! This can be due to a number of reasons, but most likely because your Python version is not supported by numpy 1.19 (https://numpy.org/doc/stable/release/1.19.5-notes.html). As a general suggestion, Python 3.8 might work better in terms of library compatibility, based on experience of previous users. 

Let me know if this helps!
