### ISSUE TITLE
Program taking too long

### ISSUE THREAD

**Issue by likpole** [sollan/alma#37]
I am currently attempting to analyze a few spontaneous mouse walking videos and have attached one of the DeepLabCut outputs. I have set the settings as shown below in the Python 3.10 environment. However, the ALMA program has been running for 2 days and I have yet to get any outputs. I was hoping you could help me and maybe give me a solution to run the program faster. Please let me know if you need anything else to help me!

![image](https://github.com/sollan/alma/assets/153773910/b6250c8b-f4d3-4efb-a92a-204bed1eee41)
![image](https://github.com/sollan/alma/assets/153773910/be378f8e-4791-469b-bfc9-14adda8d9c21)

**Comment by sollan** [comment]
Hi! It looks like your file contains a lot of datapoints with low likelihood (meaning that the DLC prediction is of low quality). Please look at the DLC output (labelled videos would be easiest way to visualize the model quality) and check if you need to retrain the model. 

If the model is fine but the recording contains too many periods that you don't need (for example, when the animal is out of the frame / acting abnormally), it's better to pause / resume during recording to get only meaningful data. Otherwise, you could crop the video after recording to durations with meaningful data. 

I also noticed you are using the fully automated mode with the default 1 px / frame treadmill speed setting, which should be provided by you and is critical for the analysis. Please check the config.yaml file and make sure you've updated the parameters according to your experiment conditions.
